env:
  global:
    - CI_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=QYfme8TdgCYkeBBRMw2TdtvKpkMeH2CCl

language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8

after_success:
  - gradle jacocoTestReport coveralls
